### PR TITLE
Ft create ui page that shows election result 163477773

### PR DESCRIPTION
**Pull request by Jesse-efe**
#### What does this PR do?
Create page where user can see election results
#### Description of Task to be completed?
Page shows all government offices and result for each office

Pages are all linked together

Page is responsive
#### How should this be manually tested?
N/A
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#163477773
#### Screenshots
one
one

one

#### Questions:
N/A

### CODE REVIEW

**Comment by megame24** [comment]
Good job, I know from the numbers, we can figure out the winner, but don't you feel indicating the winner in a way will improve user experience

**Comment by megame24** [comment]
How come you have 22 files changed?

**Comment by Jesse-efe** [comment]
OK I wud Indicate the winner. 22 files changed because in all the html pages I updated their links, also i created a new file

**Review by megame24 — APPROVED** [review]
Looks good, you can merge

**Comment by Jesse-efe** [comment]
Thank you

**Pull request merged**
