### PR TITLE
163592875 update project README

### PR DESCRIPTION
**Pull request by Jesse-efe**
#### What does this PR do?
Add more details to README.md
#### Description of Task to be completed?
Add more details to README.md
#### How should this be manually tested?
N/A
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#163592875
#### Screenshots
N/A

#### Questions:
N/A

### CODE REVIEW

**Review by akinwale-habibullah — COMMENTED** [review]
I see you're not using ESLint in your repo. Any reason why? @Jesse-efe

**Comment by Jesse-efe** [comment]
I am using it ..its only that it was not configured properly initially. But I have fixed that. In my next push I would lint my files properly

**Comment by akinwale-habibullah** [comment]
Ok. I will like you to add .eslint config file in your project root @Jesse-efe 

👍

**Comment by Jesse-efe** [comment]
OK I will

**Review by akinwale-habibullah — APPROVED** [review]

**Pull request merged**
