### PR TITLE
feat(design/template): admin page to create a political party

### PR DESCRIPTION
**Pull request by Jesse-efe**
#### What does this PR do?
Create page where admin can create a political party
#### Description of Task to be completed?
Page has a form for admin to input party details
#### How should this be manually tested?
N/A
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#163351313
#### Screenshots
one

#### Questions:
N/A

### CODE REVIEW

**Comment by megame24** [comment]
Let's adopt white text inside all blue buttons going forward.

**Comment by Jesse-efe** [comment]
Ok, changing them now

**Review by megame24 — APPROVED** [review]
Looks good, you can merge

**Comment by Jesse-efe** [comment]
Thanks

**Pull request merged**
