### PR TITLE
Ft user should see all politicians running for an office 163351686

### PR DESCRIPTION
**Pull request by Jesse-efe**
#### What does this PR do?
Create page where user can see all politicians running for an office
#### Description of Task to be completed?
Page shows all government offices

User can see all politicians running for an office

User can vote for any politician

Page is responsive
#### How should this be manually tested?
N/A
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#163351686
#### Screenshots
one
two

#### Questions:
N/A

### CODE REVIEW

**Comment by megame24** [comment]
Don't you feel that the blue button should have a different text color, the text in the button is not very visible? Also can't you come up with other offices apart from `President Federal Republic of Nigeria`?

**Comment by Jesse-efe** [comment]
Yea I was trying to maintain a consistent color, would try another color now. I will add other offices too

**Review by megame24 — APPROVED** [review]
looks good, you can merge

**Comment by Jesse-efe** [comment]
Thank you

**Pull request merged**
